/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videojuegos;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import sistemas.expertos.Menu;
import vehiculos.SistemaVehiculos;
import vehiculos.Vehiculo;

/**
 *
 * @author guss
 */
public class HaciaAtras extends javax.swing.JFrame {

    /**
     * Creates new form HaciaAtras
     */
    String preguntas[][]= new String[][]{{
                        "Tipo moba \n "+
                        "¿A usted le gusta jugar? si \n "+
                        "¿Tienes experiencia en juegos? si \n "+
                        "¿Le gusta trabajar en equipo? si \n "+
                        "¿Le gustan los juegos donde se requiere pensar arduamente? si \n "+
                        "¿Te gusta jugar online? si \n "+
                        "¿Pasas mucho tiempo jugando? si \n \n","Tipo moba"},{
        
                        "Tipo deportes \n " +
                        "¿Usted le gustan los deportes? si\n " +
                        "¿Le gusta jugar en equipo? si\n " +
                        "¿Le gusta jugar online? si\n " +
                        "¿Le gusta jugan con sus amigos? si\n " +
                        "¿Pasa mucho tiempo jugando? si\n " +
                        "¿Tiene habilidad para jugar? si\n " + 
                        "¿Le gusta jugar por tiempos? si\n " +
                        "¿Le gusta participar en torneos? si\n \n " ,"Tipo deportes"},{
                        
                        "Tipo shooter \n " +
                        "¿Usted le gustan las pistolas? si\n " +
                        "¿Usted le gusta la guerra? si\n " +
                        "¿Es una persona sangunaria? si\n " +
                        "¿Sabe de historia? si\n " + 
                        "¿Le gusta los juegos con misiones? si\n \n ","Tipo shooter"
            }};
    public HaciaAtras() {
        initComponents();
        for (int i = 0; i < preguntas.length; i++) {
            area.setText(area.getText() + preguntas[i][0]);
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cont =0;
        int pregunta = 0;
        for (int i = 0; i < preguntas.length; i++) {
            if (preguntas[i][0].toString().indexOf(area.getSelectedText())!= -1) 
            {
                pregunta= i;
                cont++;
            }
        }
        if (cont==1)
        {
            JOptionPane.showMessageDialog(this,"Se encontro el tipo: "+ preguntas[pregunta][1]);

            JOptionPane.showMessageDialog(this,preguntas[pregunta][0]);

        }else
        {
            JOptionPane.showMessageDialog(this,"Las caracteristicas seleccionadas no son \n suficientes para determinar un tipo de videojuego");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HaciaAtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HaciaAtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HaciaAtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HaciaAtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HaciaAtras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
