/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiculos;

/**
 *
 * @author ali
 */
public class Pregunta5 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta5
     */
    public Pregunta5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numPasajeros = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        dos = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        seis = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(250, 200));
        setMinimumSize(new java.awt.Dimension(250, 200));
        setPreferredSize(new java.awt.Dimension(250, 200));

        jLabel1.setText("¿Cual es su capacidad de pasajeros?");

        numPasajeros.add(dos);
        dos.setText("2");
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        numPasajeros.add(jRadioButton3);
        jRadioButton3.setText("4");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        numPasajeros.add(seis);
        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(dos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seis)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dos)
                    .addComponent(jRadioButton3)
                    .addComponent(seis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        SistemaVehiculos.vehiculos= Main.preguntaPasajeros(SistemaVehiculos.vehiculos, 2);
        SistemaVehiculos.verificarCantidad(this,new Pregunta1());
    }//GEN-LAST:event_dosActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        SistemaVehiculos.vehiculos= Main.preguntaPasajeros(SistemaVehiculos.vehiculos, 4);
        SistemaVehiculos.verificarCantidad(this,new Pregunta1());
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        SistemaVehiculos.vehiculos= Main.preguntaPasajeros(SistemaVehiculos.vehiculos, 6);
        SistemaVehiculos.verificarCantidad(this,new Pregunta1());
    }//GEN-LAST:event_seisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton dos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.ButtonGroup numPasajeros;
    public static javax.swing.JRadioButton seis;
    // End of variables declaration//GEN-END:variables
}
